name: Linter

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - 'main'

jobs:
  check-links:
    name: Linkspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          filter_mode: nofilter
          fail_on_error: true

  spellcheck:
    name: Spell checker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Typo CI 
      uses: typoci/spellcheck-action@master